bin/backlight: Make it more readable shell script

diff --git a/bin/backlight b/bin/backlight
--- a/bin/backlight
+++ b/bin/backlight
@@ -1,16 +1,23 @@
 #!/bin/sh
 
-path=/sys/class/backlight
-if [ -d "$path/intel_backlight" ]
-then
-	file=$path/intel_backlight/brightness
-elif [ -d "$path/acpi_video0" ]
-then
-	file=$path/acpi_video0/brightness
-else
-	echo "can't find device"
-	exit 1
-fi
+brightness=${1:-10}
+
+lookup()
+{
+	local path=$1
+
+	if [ -d "$path/intel_backlight" ]; then
+		file=$path/intel_backlight/brightness
+	elif [ -d "$path/acpi_video0" ]; then
+		file=$path/acpi_video0/brightness
+	else
+		echo "can't find device" >&2
+		exit 1
+	fi
+}
+
+## Lookup the device file.
+lookup /sys/class/backlight
 
 current=$(cat $file)
-sudo sh -c "echo $((current + $1)) > $file"
+sudo sh -c "echo $((current + $brightness)) > $file"
